swagger: "2.0"
info:
  description: ""
  version: 1.0.0
  title: API Docs
tags:
  - name: category
    description: CRUD
schemes:
  - http
paths:
  /categories:
    post:
      tags:
        - category
      summary: Create a new Category.
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: Accept
          schema:
            type: string
          required: true
        - in: body
          name: body
          description: Category that needs to be added to the database
          required: true
          schema:
            $ref: "#/definitions/CreateCategory"
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/ApiResponse"
        "201":
          description: Created
          schema:
            $ref: "#/definitions/ApiResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ApiResponse"
    get:
      tags:
      - category
      summary: Get a list of all categories
      description: ""
      produces:
      - application/json
      parameters:
        - in: header
          name: Accept
          schema:
            type: string
          required: true
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/Categories"
            type: array
            Categories:
              type: object
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/ApiResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ApiResponse"
    put:
      tags:
        - category
      summary: Update an existing category
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: Accept
          schema:
            type: string
          required: true
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/UpdateCategory"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/ApiResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ApiResponse"
  /categories/{category_id}:
    get:
      tags:
        - category
      summary: Find category by ID
      description: Returns a single category
      produces:
        - application/json
      parameters:
        - in: header
          name: Accept
          schema:
            type: string
          required: true
        - name: category_id
          in: path
          description: this value is get by url
          required: true
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/Category"
        "404":
          description: Not Found
          schema :
            $ref: "#/definitions/ApiResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ApiResponse"
    delete:
      tags:
        - category
      summary: Delete a category By Id
      description: ""
      parameters:
        - in: header
          name: Accept
          schema:
            type: string
          required: true
        - name: category_id
          in: path
          description: this value is get by url
          required: true
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
        "404":
          description: Not Found
          schema :
            $ref: "#/definitions/ApiResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ApiResponse"
definitions:
  CreateCategory:
    properties:
      name:
        type: string
  UpdateCategory:
    properties:
      id:
        type: string
      name:
        type: string
  Category:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
    example:
      - id: "d11002bf-359c-4b42-a73d-6fcac4584c63"
        name: "sports"
        created_at: "2019-02-06T15:13:28.917051+05:30"
        updated_at: "2019-02-06T15:13:28.917051+05:30"
  Categories:
    type: object
    properties:
      Category:
        type: array
        items:
          $ref: ''
        example:
          - id: "d11002bf-359c-4b42-a73d-6fcac4584c63"
            name: "sports"
            created_at: "2019-02-06T15:13:28.917051+05:30"
            updated_at: "2019-02-06T15:13:28.917051+05:30"
          - id: "149d1920-5ee8-4661-993a-b8501ae31889"
            name: "Bill"
            created_at: "2019-02-06T15:43:35.361133+05:30"
            updated_at: "2019-02-06T15:43:35.361133+05:30"
  ApiResponse:
    properties:
      message:
        type: string
    xml:
      name: "##default"
